# CREATE DOCKER IMAGE
# docker build -t <image_name> --build-arg INSTALL_GAZEBO=true .
# CREATE DOCKER CONTAINER
# docker run -it --name <container_name> -v $PWD:/home/ros/ros2_ws -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY --network host <image_name>
FROM osrf/ros:humble-desktop
ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG INSTALL_GAZEBO=false

# Create non-root user + sudo
RUN groupadd --gid $USER_GID $USERNAME \
 && useradd -m -s /bin/bash --uid $USER_UID --gid $USER_GID $USERNAME \
 && apt-get update \
 && apt-get install -y sudo \
 && echo "$USERNAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
 && chmod 0440 /etc/sudoers.d/$USERNAME \
 && rm -rf /var/lib/apt/lists/*

# System dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    ros-humble-teleop-twist-keyboard \
    xterm \
    && rm -rf /var/lib/apt/lists/*

# Gazebo
RUN if [ "$INSTALL_GAZEBO" = "true" ]; then \
    apt-get update && apt-get install -y \
        ros-humble-turtlebot4-simulator \
        ros-humble-turtlebot4-desktop \
    && rm -rf /var/lib/apt/lists/* ; \
    fi

# Workspace
WORKDIR /home/ros/ros2_ws

# Source ROS
RUN echo "source /opt/ros/humble/setup.bash" >> /home/ros/.bashrc

USER ros
CMD ["bash"]
